/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData accept = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cam = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData best_rated = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calander = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carry_package = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData completed = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cost = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData current_location = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData destination = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData future = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leading_icon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_packs = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_trip = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_2 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData on_going = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData packages_carried = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData packages_received = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData packages_send = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plain = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reach_time = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reject = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData root = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scooter = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData succes = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel_time = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upi = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
